projects:
  cdk-todos-appsync-api:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-east-2
        apiId: ndd73cn35reg7k4a3zdurlqrvu
        maxDepth: 2
extensions:
  amplify:
    version: 3
